#!/usr/bin/env sh

set -e
trap "rm -f .git/tags.$$" EXIT

ctags --tag-relative -Rf.git/tags.$$ \
  --exclude=.git/\* \
  --exclude=\*.min.\* \
  --exclude=node_modules/\* \
  --exclude=vendor/\* \
  2> /dev/null &&
mv .git/tags.$$ .git/tags &
