{
    "home": {
        "eDP1": {"mode": [1920, 1080], "rotate": "normal"},
        "DP1": {"off": true},
        "HDMI2": {"mode": [3840, 2160], "right-of": "eDP1"}
    },

    "office": {
        "eDP1": {"mode": [2560, 1440], "rotate": "normal"},
        "HDMI2": {"mode": [3840, 2160], "left-of": "eDP1", "rotate": "normal"},
        "DP1": {"mode": [1920, 1080], "right-of": "eDP1", "rotate": "left"}
    },

    "standard": {
        "eDP1": {"mode": [2560, 1440], "rotate": "normal"},
        "DP1": {"off": true},
        "HDMI2": {"off": true}
    },

    "tablet": {
        "eDP1": {"mode": [2560, 1440], "rotate": "normal"},
        "DP1": {"off": true},
        "HDMI2": {"off": true}
    }
}
